package com.example.demo;

public class BC_MOD_COLLECTED_AMOUNT 
{
	String  LOCATION_CODE, LOCATION_NAME,CIRCLE_DESC, RAO_NAME,  BILL_CYCLE_CODE,
	BILL_MONTH, USAGE_CAT_NAME, CATEGORY,CUR_MONTH_COL_AMT, CUR_MONTH_COL_LPS_AMT, CUR_MONTH_COL_VAT_AMT, PREV_MONTH_BILLED_AMT,
	PREV_MONTH_RECEIVABLE_AMT, PREV_MONTH_COLLECTION_AMT, PREV_MONTH__ENERGY_SOLD, SL_NO;

	public String getLOCATION_CODE() {
		return LOCATION_CODE;
	}

	public void setLOCATION_CODE(String lOCATION_CODE) {
		LOCATION_CODE = lOCATION_CODE;
	}

	public String getLOCATION_NAME() {
		return LOCATION_NAME;
	}

	public void setLOCATION_NAME(String lOCATION_NAME) {
		LOCATION_NAME = lOCATION_NAME;
	}

	public String getCIRCLE_DESC() {
		return CIRCLE_DESC;
	}

	public void setCIRCLE_DESC(String cIRCLE_DESC) {
		CIRCLE_DESC = cIRCLE_DESC;
	}

	public String getRAO_NAME() {
		return RAO_NAME;
	}

	public void setRAO_NAME(String rAO_NAME) {
		RAO_NAME = rAO_NAME;
	}

	public String getBILL_CYCLE_CODE() {
		return BILL_CYCLE_CODE;
	}

	public void setBILL_CYCLE_CODE(String bILL_CYCLE_CODE) {
		BILL_CYCLE_CODE = bILL_CYCLE_CODE;
	}

	public String getBILL_MONTH() {
		return BILL_MONTH;
	}

	public void setBILL_MONTH(String bILL_MONTH) {
		BILL_MONTH = bILL_MONTH;
	}

	public String getUSAGE_CAT_NAME() {
		return USAGE_CAT_NAME;
	}

	public void setUSAGE_CAT_NAME(String uSAGE_CAT_NAME) {
		USAGE_CAT_NAME = uSAGE_CAT_NAME;
	}

	public String getCATEGORY() {
		return CATEGORY;
	}

	public void setCATEGORY(String cATEGORY) {
		CATEGORY = cATEGORY;
	}

	public String getCUR_MONTH_COL_AMT() {
		return CUR_MONTH_COL_AMT;
	}

	public void setCUR_MONTH_COL_AMT(String cUR_MONTH_COL_AMT) {
		CUR_MONTH_COL_AMT = cUR_MONTH_COL_AMT;
	}

	public String getCUR_MONTH_COL_LPS_AMT() {
		return CUR_MONTH_COL_LPS_AMT;
	}

	public void setCUR_MONTH_COL_LPS_AMT(String cUR_MONTH_COL_LPS_AMT) {
		CUR_MONTH_COL_LPS_AMT = cUR_MONTH_COL_LPS_AMT;
	}

	public String getCUR_MONTH_COL_VAT_AMT() {
		return CUR_MONTH_COL_VAT_AMT;
	}

	public void setCUR_MONTH_COL_VAT_AMT(String cUR_MONTH_COL_VAT_AMT) {
		CUR_MONTH_COL_VAT_AMT = cUR_MONTH_COL_VAT_AMT;
	}

	public String getPREV_MONTH_BILLED_AMT() {
		return PREV_MONTH_BILLED_AMT;
	}

	public void setPREV_MONTH_BILLED_AMT(String pREV_MONTH_BILLED_AMT) {
		PREV_MONTH_BILLED_AMT = pREV_MONTH_BILLED_AMT;
	}

	public String getPREV_MONTH_RECEIVABLE_AMT() {
		return PREV_MONTH_RECEIVABLE_AMT;
	}

	public void setPREV_MONTH_RECEIVABLE_AMT(String pREV_MONTH_RECEIVABLE_AMT) {
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
	}

	public String getPREV_MONTH_COLLECTION_AMT() {
		return PREV_MONTH_COLLECTION_AMT;
	}

	public void setPREV_MONTH_COLLECTION_AMT(String pREV_MONTH_COLLECTION_AMT) {
		PREV_MONTH_COLLECTION_AMT = pREV_MONTH_COLLECTION_AMT;
	}

	public String getPREV_MONTH__ENERGY_SOLD() {
		return PREV_MONTH__ENERGY_SOLD;
	}

	public void setPREV_MONTH__ENERGY_SOLD(String pREV_MONTH__ENERGY_SOLD) {
		PREV_MONTH__ENERGY_SOLD = pREV_MONTH__ENERGY_SOLD;
	}

	public String getSL_NO() {
		return SL_NO;
	}

	public void setSL_NO(String sL_NO) {
		SL_NO = sL_NO;
	}

	public BC_MOD_COLLECTED_AMOUNT(String lOCATION_CODE, String lOCATION_NAME, String cIRCLE_DESC, String rAO_NAME,
			String bILL_CYCLE_CODE, String bILL_MONTH, String uSAGE_CAT_NAME, String cATEGORY, String cUR_MONTH_COL_AMT,
			String cUR_MONTH_COL_LPS_AMT, String cUR_MONTH_COL_VAT_AMT, String pREV_MONTH_BILLED_AMT,
			String pREV_MONTH_RECEIVABLE_AMT, String pREV_MONTH_COLLECTION_AMT, String pREV_MONTH__ENERGY_SOLD,
			String sL_NO) {
		super();
		LOCATION_CODE = lOCATION_CODE;
		LOCATION_NAME = lOCATION_NAME;
		CIRCLE_DESC = cIRCLE_DESC;
		RAO_NAME = rAO_NAME;
		BILL_CYCLE_CODE = bILL_CYCLE_CODE;
		BILL_MONTH = bILL_MONTH;
		USAGE_CAT_NAME = uSAGE_CAT_NAME;
		CATEGORY = cATEGORY;
		CUR_MONTH_COL_AMT = cUR_MONTH_COL_AMT;
		CUR_MONTH_COL_LPS_AMT = cUR_MONTH_COL_LPS_AMT;
		CUR_MONTH_COL_VAT_AMT = cUR_MONTH_COL_VAT_AMT;
		PREV_MONTH_BILLED_AMT = pREV_MONTH_BILLED_AMT;
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
		PREV_MONTH_COLLECTION_AMT = pREV_MONTH_COLLECTION_AMT;
		PREV_MONTH__ENERGY_SOLD = pREV_MONTH__ENERGY_SOLD;
		SL_NO = sL_NO;
	}

	public BC_MOD_COLLECTED_AMOUNT() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "BC_MOD_COLLECTED_AMOUNT [LOCATION_CODE=" + LOCATION_CODE + ", LOCATION_NAME=" + LOCATION_NAME
				+ ", CIRCLE_DESC=" + CIRCLE_DESC + ", RAO_NAME=" + RAO_NAME + ", BILL_CYCLE_CODE=" + BILL_CYCLE_CODE
				+ ", BILL_MONTH=" + BILL_MONTH + ", USAGE_CAT_NAME=" + USAGE_CAT_NAME + ", CATEGORY=" + CATEGORY
				+ ", CUR_MONTH_COL_AMT=" + CUR_MONTH_COL_AMT + ", CUR_MONTH_COL_LPS_AMT=" + CUR_MONTH_COL_LPS_AMT
				+ ", CUR_MONTH_COL_VAT_AMT=" + CUR_MONTH_COL_VAT_AMT + ", PREV_MONTH_BILLED_AMT="
				+ PREV_MONTH_BILLED_AMT + ", PREV_MONTH_RECEIVABLE_AMT=" + PREV_MONTH_RECEIVABLE_AMT
				+ ", PREV_MONTH_COLLECTION_AMT=" + PREV_MONTH_COLLECTION_AMT + ", PREV_MONTH__ENERGY_SOLD="
				+ PREV_MONTH__ENERGY_SOLD + ", SL_NO=" + SL_NO + "]";
	}

	
	
	
}
