package com.example.demo;

public class BC_MOD_SUMMERY_REPORT
{
	String LOCATION_CODE, LOCATION_NAME, CIRCLE_DESC, RAO_NAME,  BILL_CYCLE_CODE, BILL_CYCLE_DESCR, NO_OF_CONSUMER,
	NO_OF_CONSUMER_PREV_MONTH, NO_OF_CONSUMER_BILLED, NO_OF_CONS_BILLED_PREV_MONTH, NET_ENERGY_IMP_KWH,
	NET_ENERGY_IMP_KWH_PREV, NET_ENERGY_GEN_KWH, TOTAL_IMPORT,
	TOTAL_IMPORT_PREV, TOTAL_ENERGY_SOLD_TO_CONS, TOTAL_ENERGY_SOLD_PREV_MONTH, ENERGY_LOST, ENERGY_LOST_PREV,
	SYSTEM_LOSS,SYSTEM_LOSS_PREV, TOTAL_GROSS_BILLED_AMT,TOTAL_GROSS_BILLED_PREV_MONTH,
	TOTAL_NET_BILLED_AMT, TOTAL_NET_BILLED_PREV_MONTH, TOTAL_LPS_BILLED_AMT,TOTAL_LPS_BILLED_PREV_MONTH, TOTAL_GROSS_PRN_COLLECTED_AMT,
	TOTAL_GROSS_PRN_COLL_PREV_MON, TOTAL_GROSS_LPS_COLLECTED_AMT, TOTAL_GROSS_LPS_COLL_PREV_MON, TOTAL_GROSS_COLLECTED_AMT,
	TOTAL_GROSS_COLL_PREV_MONTH,CI_RATIO, CI_RATIO_PREV, AC_RECEIVABLE, AC_RECEIVABLE_PREV_MONTH, AC_RECEIVABLE_PRN_CUR_MON, AC_RECEIVABLE_PRN_PREV_MONTH,
	AC_RECEIVABLE_LPS_CUR_MON, AC_RECEIVABLE_LPS_PREV_MONTH, REB_STATISTICS, ENERGY_EXP_SOLD_TO_REB, BILLED_AMT_TO_REB, COLL_AMT_F_REB,
	AC_RECEIVABLE_F_REB, SYSTEM_LOSS_WITHOUT_REB, CI_RATIO_WITHOUT_REB, BPDB_ESU_BILLING_RATE, BPDB_ESU_BILLING_RATE_PREV, LIVE_CONSUMER_PREV_MONTH, PREV_NO_OF_CONS_BILLED, 
	PREV_MONTH_ENERGY_SOLD, PREV_MONTH_RECEIVABLE_AMT;

	public String getLOCATION_CODE() {
		return LOCATION_CODE;
	}

	public void setLOCATION_CODE(String lOCATION_CODE) {
		LOCATION_CODE = lOCATION_CODE;
	}

	public String getLOCATION_NAME() {
		return LOCATION_NAME;
	}

	public void setLOCATION_NAME(String lOCATION_NAME) {
		LOCATION_NAME = lOCATION_NAME;
	}

	public String getCIRCLE_DESC() {
		return CIRCLE_DESC;
	}

	public void setCIRCLE_DESC(String cIRCLE_DESC) {
		CIRCLE_DESC = cIRCLE_DESC;
	}

	public String getRAO_NAME() {
		return RAO_NAME;
	}

	public void setRAO_NAME(String rAO_NAME) {
		RAO_NAME = rAO_NAME;
	}

	public String getBILL_CYCLE_CODE() {
		return BILL_CYCLE_CODE;
	}

	public void setBILL_CYCLE_CODE(String bILL_CYCLE_CODE) {
		BILL_CYCLE_CODE = bILL_CYCLE_CODE;
	}

	public String getBILL_CYCLE_DESCR() {
		return BILL_CYCLE_DESCR;
	}

	public void setBILL_CYCLE_DESCR(String bILL_CYCLE_DESCR) {
		BILL_CYCLE_DESCR = bILL_CYCLE_DESCR;
	}

	public String getNO_OF_CONSUMER() {
		return NO_OF_CONSUMER;
	}

	public void setNO_OF_CONSUMER(String nO_OF_CONSUMER) {
		NO_OF_CONSUMER = nO_OF_CONSUMER;
	}

	public String getNO_OF_CONSUMER_PREV_MONTH() {
		return NO_OF_CONSUMER_PREV_MONTH;
	}

	public void setNO_OF_CONSUMER_PREV_MONTH(String nO_OF_CONSUMER_PREV_MONTH) {
		NO_OF_CONSUMER_PREV_MONTH = nO_OF_CONSUMER_PREV_MONTH;
	}

	public String getNO_OF_CONSUMER_BILLED() {
		return NO_OF_CONSUMER_BILLED;
	}

	public void setNO_OF_CONSUMER_BILLED(String nO_OF_CONSUMER_BILLED) {
		NO_OF_CONSUMER_BILLED = nO_OF_CONSUMER_BILLED;
	}

	public String getNO_OF_CONS_BILLED_PREV_MONTH() {
		return NO_OF_CONS_BILLED_PREV_MONTH;
	}

	public void setNO_OF_CONS_BILLED_PREV_MONTH(String nO_OF_CONS_BILLED_PREV_MONTH) {
		NO_OF_CONS_BILLED_PREV_MONTH = nO_OF_CONS_BILLED_PREV_MONTH;
	}

	public String getNET_ENERGY_IMP_KWH() {
		return NET_ENERGY_IMP_KWH;
	}

	public void setNET_ENERGY_IMP_KWH(String nET_ENERGY_IMP_KWH) {
		NET_ENERGY_IMP_KWH = nET_ENERGY_IMP_KWH;
	}

	public String getNET_ENERGY_IMP_KWH_PREV() {
		return NET_ENERGY_IMP_KWH_PREV;
	}

	public void setNET_ENERGY_IMP_KWH_PREV(String nET_ENERGY_IMP_KWH_PREV) {
		NET_ENERGY_IMP_KWH_PREV = nET_ENERGY_IMP_KWH_PREV;
	}

	public String getNET_ENERGY_GEN_KWH() {
		return NET_ENERGY_GEN_KWH;
	}

	public void setNET_ENERGY_GEN_KWH(String nET_ENERGY_GEN_KWH) {
		NET_ENERGY_GEN_KWH = nET_ENERGY_GEN_KWH;
	}

	public String getTOTAL_IMPORT() {
		return TOTAL_IMPORT;
	}

	public void setTOTAL_IMPORT(String tOTAL_IMPORT) {
		TOTAL_IMPORT = tOTAL_IMPORT;
	}

	public String getTOTAL_IMPORT_PREV() {
		return TOTAL_IMPORT_PREV;
	}

	public void setTOTAL_IMPORT_PREV(String tOTAL_IMPORT_PREV) {
		TOTAL_IMPORT_PREV = tOTAL_IMPORT_PREV;
	}

	public String getTOTAL_ENERGY_SOLD_TO_CONS() {
		return TOTAL_ENERGY_SOLD_TO_CONS;
	}

	public void setTOTAL_ENERGY_SOLD_TO_CONS(String tOTAL_ENERGY_SOLD_TO_CONS) {
		TOTAL_ENERGY_SOLD_TO_CONS = tOTAL_ENERGY_SOLD_TO_CONS;
	}

	public String getTOTAL_ENERGY_SOLD_PREV_MONTH() {
		return TOTAL_ENERGY_SOLD_PREV_MONTH;
	}

	public void setTOTAL_ENERGY_SOLD_PREV_MONTH(String tOTAL_ENERGY_SOLD_PREV_MONTH) {
		TOTAL_ENERGY_SOLD_PREV_MONTH = tOTAL_ENERGY_SOLD_PREV_MONTH;
	}

	public String getENERGY_LOST() {
		return ENERGY_LOST;
	}

	public void setENERGY_LOST(String eNERGY_LOST) {
		ENERGY_LOST = eNERGY_LOST;
	}

	public String getENERGY_LOST_PREV() {
		return ENERGY_LOST_PREV;
	}

	public void setENERGY_LOST_PREV(String eNERGY_LOST_PREV) {
		ENERGY_LOST_PREV = eNERGY_LOST_PREV;
	}

	public String getSYSTEM_LOSS() {
		return SYSTEM_LOSS;
	}

	public void setSYSTEM_LOSS(String sYSTEM_LOSS) {
		SYSTEM_LOSS = sYSTEM_LOSS;
	}

	public String getSYSTEM_LOSS_PREV() {
		return SYSTEM_LOSS_PREV;
	}

	public void setSYSTEM_LOSS_PREV(String sYSTEM_LOSS_PREV) {
		SYSTEM_LOSS_PREV = sYSTEM_LOSS_PREV;
	}

	public String getTOTAL_GROSS_BILLED_AMT() {
		return TOTAL_GROSS_BILLED_AMT;
	}

	public void setTOTAL_GROSS_BILLED_AMT(String tOTAL_GROSS_BILLED_AMT) {
		TOTAL_GROSS_BILLED_AMT = tOTAL_GROSS_BILLED_AMT;
	}

	public String getTOTAL_GROSS_BILLED_PREV_MONTH() {
		return TOTAL_GROSS_BILLED_PREV_MONTH;
	}

	public void setTOTAL_GROSS_BILLED_PREV_MONTH(String tOTAL_GROSS_BILLED_PREV_MONTH) {
		TOTAL_GROSS_BILLED_PREV_MONTH = tOTAL_GROSS_BILLED_PREV_MONTH;
	}

	public String getTOTAL_NET_BILLED_AMT() {
		return TOTAL_NET_BILLED_AMT;
	}

	public void setTOTAL_NET_BILLED_AMT(String tOTAL_NET_BILLED_AMT) {
		TOTAL_NET_BILLED_AMT = tOTAL_NET_BILLED_AMT;
	}

	public String getTOTAL_NET_BILLED_PREV_MONTH() {
		return TOTAL_NET_BILLED_PREV_MONTH;
	}

	public void setTOTAL_NET_BILLED_PREV_MONTH(String tOTAL_NET_BILLED_PREV_MONTH) {
		TOTAL_NET_BILLED_PREV_MONTH = tOTAL_NET_BILLED_PREV_MONTH;
	}

	public String getTOTAL_LPS_BILLED_AMT() {
		return TOTAL_LPS_BILLED_AMT;
	}

	public void setTOTAL_LPS_BILLED_AMT(String tOTAL_LPS_BILLED_AMT) {
		TOTAL_LPS_BILLED_AMT = tOTAL_LPS_BILLED_AMT;
	}

	public String getTOTAL_LPS_BILLED_PREV_MONTH() {
		return TOTAL_LPS_BILLED_PREV_MONTH;
	}

	public void setTOTAL_LPS_BILLED_PREV_MONTH(String tOTAL_LPS_BILLED_PREV_MONTH) {
		TOTAL_LPS_BILLED_PREV_MONTH = tOTAL_LPS_BILLED_PREV_MONTH;
	}

	public String getTOTAL_GROSS_PRN_COLLECTED_AMT() {
		return TOTAL_GROSS_PRN_COLLECTED_AMT;
	}

	public void setTOTAL_GROSS_PRN_COLLECTED_AMT(String tOTAL_GROSS_PRN_COLLECTED_AMT) {
		TOTAL_GROSS_PRN_COLLECTED_AMT = tOTAL_GROSS_PRN_COLLECTED_AMT;
	}

	public String getTOTAL_GROSS_PRN_COLL_PREV_MON() {
		return TOTAL_GROSS_PRN_COLL_PREV_MON;
	}

	public void setTOTAL_GROSS_PRN_COLL_PREV_MON(String tOTAL_GROSS_PRN_COLL_PREV_MON) {
		TOTAL_GROSS_PRN_COLL_PREV_MON = tOTAL_GROSS_PRN_COLL_PREV_MON;
	}

	public String getTOTAL_GROSS_LPS_COLLECTED_AMT() {
		return TOTAL_GROSS_LPS_COLLECTED_AMT;
	}

	public void setTOTAL_GROSS_LPS_COLLECTED_AMT(String tOTAL_GROSS_LPS_COLLECTED_AMT) {
		TOTAL_GROSS_LPS_COLLECTED_AMT = tOTAL_GROSS_LPS_COLLECTED_AMT;
	}

	public String getTOTAL_GROSS_LPS_COLL_PREV_MON() {
		return TOTAL_GROSS_LPS_COLL_PREV_MON;
	}

	public void setTOTAL_GROSS_LPS_COLL_PREV_MON(String tOTAL_GROSS_LPS_COLL_PREV_MON) {
		TOTAL_GROSS_LPS_COLL_PREV_MON = tOTAL_GROSS_LPS_COLL_PREV_MON;
	}

	public String getTOTAL_GROSS_COLLECTED_AMT() {
		return TOTAL_GROSS_COLLECTED_AMT;
	}

	public void setTOTAL_GROSS_COLLECTED_AMT(String tOTAL_GROSS_COLLECTED_AMT) {
		TOTAL_GROSS_COLLECTED_AMT = tOTAL_GROSS_COLLECTED_AMT;
	}

	public String getTOTAL_GROSS_COLL_PREV_MONTH() {
		return TOTAL_GROSS_COLL_PREV_MONTH;
	}

	public void setTOTAL_GROSS_COLL_PREV_MONTH(String tOTAL_GROSS_COLL_PREV_MONTH) {
		TOTAL_GROSS_COLL_PREV_MONTH = tOTAL_GROSS_COLL_PREV_MONTH;
	}

	public String getCI_RATIO() {
		return CI_RATIO;
	}

	public void setCI_RATIO(String cI_RATIO) {
		CI_RATIO = cI_RATIO;
	}

	public String getCI_RATIO_PREV() {
		return CI_RATIO_PREV;
	}

	public void setCI_RATIO_PREV(String cI_RATIO_PREV) {
		CI_RATIO_PREV = cI_RATIO_PREV;
	}

	public String getAC_RECEIVABLE() {
		return AC_RECEIVABLE;
	}

	public void setAC_RECEIVABLE(String aC_RECEIVABLE) {
		AC_RECEIVABLE = aC_RECEIVABLE;
	}

	public String getAC_RECEIVABLE_PREV_MONTH() {
		return AC_RECEIVABLE_PREV_MONTH;
	}

	public void setAC_RECEIVABLE_PREV_MONTH(String aC_RECEIVABLE_PREV_MONTH) {
		AC_RECEIVABLE_PREV_MONTH = aC_RECEIVABLE_PREV_MONTH;
	}

	public String getAC_RECEIVABLE_PRN_CUR_MON() {
		return AC_RECEIVABLE_PRN_CUR_MON;
	}

	public void setAC_RECEIVABLE_PRN_CUR_MON(String aC_RECEIVABLE_PRN_CUR_MON) {
		AC_RECEIVABLE_PRN_CUR_MON = aC_RECEIVABLE_PRN_CUR_MON;
	}

	public String getAC_RECEIVABLE_PRN_PREV_MONTH() {
		return AC_RECEIVABLE_PRN_PREV_MONTH;
	}

	public void setAC_RECEIVABLE_PRN_PREV_MONTH(String aC_RECEIVABLE_PRN_PREV_MONTH) {
		AC_RECEIVABLE_PRN_PREV_MONTH = aC_RECEIVABLE_PRN_PREV_MONTH;
	}

	public String getAC_RECEIVABLE_LPS_CUR_MON() {
		return AC_RECEIVABLE_LPS_CUR_MON;
	}

	public void setAC_RECEIVABLE_LPS_CUR_MON(String aC_RECEIVABLE_LPS_CUR_MON) {
		AC_RECEIVABLE_LPS_CUR_MON = aC_RECEIVABLE_LPS_CUR_MON;
	}

	public String getAC_RECEIVABLE_LPS_PREV_MONTH() {
		return AC_RECEIVABLE_LPS_PREV_MONTH;
	}

	public void setAC_RECEIVABLE_LPS_PREV_MONTH(String aC_RECEIVABLE_LPS_PREV_MONTH) {
		AC_RECEIVABLE_LPS_PREV_MONTH = aC_RECEIVABLE_LPS_PREV_MONTH;
	}

	public String getREB_STATISTICS() {
		return REB_STATISTICS;
	}

	public void setREB_STATISTICS(String rEB_STATISTICS) {
		REB_STATISTICS = rEB_STATISTICS;
	}

	public String getENERGY_EXP_SOLD_TO_REB() {
		return ENERGY_EXP_SOLD_TO_REB;
	}

	public void setENERGY_EXP_SOLD_TO_REB(String eNERGY_EXP_SOLD_TO_REB) {
		ENERGY_EXP_SOLD_TO_REB = eNERGY_EXP_SOLD_TO_REB;
	}

	public String getBILLED_AMT_TO_REB() {
		return BILLED_AMT_TO_REB;
	}

	public void setBILLED_AMT_TO_REB(String bILLED_AMT_TO_REB) {
		BILLED_AMT_TO_REB = bILLED_AMT_TO_REB;
	}

	public String getCOLL_AMT_F_REB() {
		return COLL_AMT_F_REB;
	}

	public void setCOLL_AMT_F_REB(String cOLL_AMT_F_REB) {
		COLL_AMT_F_REB = cOLL_AMT_F_REB;
	}

	public String getAC_RECEIVABLE_F_REB() {
		return AC_RECEIVABLE_F_REB;
	}

	public void setAC_RECEIVABLE_F_REB(String aC_RECEIVABLE_F_REB) {
		AC_RECEIVABLE_F_REB = aC_RECEIVABLE_F_REB;
	}

	public String getSYSTEM_LOSS_WITHOUT_REB() {
		return SYSTEM_LOSS_WITHOUT_REB;
	}

	public void setSYSTEM_LOSS_WITHOUT_REB(String sYSTEM_LOSS_WITHOUT_REB) {
		SYSTEM_LOSS_WITHOUT_REB = sYSTEM_LOSS_WITHOUT_REB;
	}

	public String getCI_RATIO_WITHOUT_REB() {
		return CI_RATIO_WITHOUT_REB;
	}

	public void setCI_RATIO_WITHOUT_REB(String cI_RATIO_WITHOUT_REB) {
		CI_RATIO_WITHOUT_REB = cI_RATIO_WITHOUT_REB;
	}

	public String getBPDB_ESU_BILLING_RATE() {
		return BPDB_ESU_BILLING_RATE;
	}

	public void setBPDB_ESU_BILLING_RATE(String bPDB_ESU_BILLING_RATE) {
		BPDB_ESU_BILLING_RATE = bPDB_ESU_BILLING_RATE;
	}

	public String getBPDB_ESU_BILLING_RATE_PREV() {
		return BPDB_ESU_BILLING_RATE_PREV;
	}

	public void setBPDB_ESU_BILLING_RATE_PREV(String bPDB_ESU_BILLING_RATE_PREV) {
		BPDB_ESU_BILLING_RATE_PREV = bPDB_ESU_BILLING_RATE_PREV;
	}

	public String getLIVE_CONSUMER_PREV_MONTH() {
		return LIVE_CONSUMER_PREV_MONTH;
	}

	public void setLIVE_CONSUMER_PREV_MONTH(String lIVE_CONSUMER_PREV_MONTH) {
		LIVE_CONSUMER_PREV_MONTH = lIVE_CONSUMER_PREV_MONTH;
	}

	public String getPREV_NO_OF_CONS_BILLED() {
		return PREV_NO_OF_CONS_BILLED;
	}

	public void setPREV_NO_OF_CONS_BILLED(String pREV_NO_OF_CONS_BILLED) {
		PREV_NO_OF_CONS_BILLED = pREV_NO_OF_CONS_BILLED;
	}

	public String getPREV_MONTH_ENERGY_SOLD() {
		return PREV_MONTH_ENERGY_SOLD;
	}

	public void setPREV_MONTH_ENERGY_SOLD(String pREV_MONTH_ENERGY_SOLD) {
		PREV_MONTH_ENERGY_SOLD = pREV_MONTH_ENERGY_SOLD;
	}

	public String getPREV_MONTH_RECEIVABLE_AMT() {
		return PREV_MONTH_RECEIVABLE_AMT;
	}

	public void setPREV_MONTH_RECEIVABLE_AMT(String pREV_MONTH_RECEIVABLE_AMT) {
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
	}

	@Override
	public String toString() {
		return "BC_MOD_SUMMERY_REPORT [LOCATION_CODE=" + LOCATION_CODE + ", LOCATION_NAME=" + LOCATION_NAME
				+ ", CIRCLE_DESC=" + CIRCLE_DESC + ", RAO_NAME=" + RAO_NAME + ", BILL_CYCLE_CODE=" + BILL_CYCLE_CODE
				+ ", BILL_CYCLE_DESCR=" + BILL_CYCLE_DESCR + ", NO_OF_CONSUMER=" + NO_OF_CONSUMER
				+ ", NO_OF_CONSUMER_PREV_MONTH=" + NO_OF_CONSUMER_PREV_MONTH + ", NO_OF_CONSUMER_BILLED="
				+ NO_OF_CONSUMER_BILLED + ", NO_OF_CONS_BILLED_PREV_MONTH=" + NO_OF_CONS_BILLED_PREV_MONTH
				+ ", NET_ENERGY_IMP_KWH=" + NET_ENERGY_IMP_KWH + ", NET_ENERGY_IMP_KWH_PREV=" + NET_ENERGY_IMP_KWH_PREV
				+ ", NET_ENERGY_GEN_KWH=" + NET_ENERGY_GEN_KWH + ", TOTAL_IMPORT=" + TOTAL_IMPORT
				+ ", TOTAL_IMPORT_PREV=" + TOTAL_IMPORT_PREV + ", TOTAL_ENERGY_SOLD_TO_CONS="
				+ TOTAL_ENERGY_SOLD_TO_CONS + ", TOTAL_ENERGY_SOLD_PREV_MONTH=" + TOTAL_ENERGY_SOLD_PREV_MONTH
				+ ", ENERGY_LOST=" + ENERGY_LOST + ", ENERGY_LOST_PREV=" + ENERGY_LOST_PREV + ", SYSTEM_LOSS="
				+ SYSTEM_LOSS + ", SYSTEM_LOSS_PREV=" + SYSTEM_LOSS_PREV + ", TOTAL_GROSS_BILLED_AMT="
				+ TOTAL_GROSS_BILLED_AMT + ", TOTAL_GROSS_BILLED_PREV_MONTH=" + TOTAL_GROSS_BILLED_PREV_MONTH
				+ ", TOTAL_NET_BILLED_AMT=" + TOTAL_NET_BILLED_AMT + ", TOTAL_NET_BILLED_PREV_MONTH="
				+ TOTAL_NET_BILLED_PREV_MONTH + ", TOTAL_LPS_BILLED_AMT=" + TOTAL_LPS_BILLED_AMT
				+ ", TOTAL_LPS_BILLED_PREV_MONTH=" + TOTAL_LPS_BILLED_PREV_MONTH + ", TOTAL_GROSS_PRN_COLLECTED_AMT="
				+ TOTAL_GROSS_PRN_COLLECTED_AMT + ", TOTAL_GROSS_PRN_COLL_PREV_MON=" + TOTAL_GROSS_PRN_COLL_PREV_MON
				+ ", TOTAL_GROSS_LPS_COLLECTED_AMT=" + TOTAL_GROSS_LPS_COLLECTED_AMT
				+ ", TOTAL_GROSS_LPS_COLL_PREV_MON=" + TOTAL_GROSS_LPS_COLL_PREV_MON + ", TOTAL_GROSS_COLLECTED_AMT="
				+ TOTAL_GROSS_COLLECTED_AMT + ", TOTAL_GROSS_COLL_PREV_MONTH=" + TOTAL_GROSS_COLL_PREV_MONTH
				+ ", CI_RATIO=" + CI_RATIO + ", CI_RATIO_PREV=" + CI_RATIO_PREV + ", AC_RECEIVABLE=" + AC_RECEIVABLE
				+ ", AC_RECEIVABLE_PREV_MONTH=" + AC_RECEIVABLE_PREV_MONTH + ", AC_RECEIVABLE_PRN_CUR_MON="
				+ AC_RECEIVABLE_PRN_CUR_MON + ", AC_RECEIVABLE_PRN_PREV_MONTH=" + AC_RECEIVABLE_PRN_PREV_MONTH
				+ ", AC_RECEIVABLE_LPS_CUR_MON=" + AC_RECEIVABLE_LPS_CUR_MON + ", AC_RECEIVABLE_LPS_PREV_MONTH="
				+ AC_RECEIVABLE_LPS_PREV_MONTH + ", REB_STATISTICS=" + REB_STATISTICS + ", ENERGY_EXP_SOLD_TO_REB="
				+ ENERGY_EXP_SOLD_TO_REB + ", BILLED_AMT_TO_REB=" + BILLED_AMT_TO_REB + ", COLL_AMT_F_REB="
				+ COLL_AMT_F_REB + ", AC_RECEIVABLE_F_REB=" + AC_RECEIVABLE_F_REB + ", SYSTEM_LOSS_WITHOUT_REB="
				+ SYSTEM_LOSS_WITHOUT_REB + ", CI_RATIO_WITHOUT_REB=" + CI_RATIO_WITHOUT_REB
				+ ", BPDB_ESU_BILLING_RATE=" + BPDB_ESU_BILLING_RATE + ", BPDB_ESU_BILLING_RATE_PREV="
				+ BPDB_ESU_BILLING_RATE_PREV + ", LIVE_CONSUMER_PREV_MONTH=" + LIVE_CONSUMER_PREV_MONTH
				+ ", PREV_NO_OF_CONS_BILLED=" + PREV_NO_OF_CONS_BILLED + ", PREV_MONTH_ENERGY_SOLD="
				+ PREV_MONTH_ENERGY_SOLD + ", PREV_MONTH_RECEIVABLE_AMT=" + PREV_MONTH_RECEIVABLE_AMT + "]";
	}

	public BC_MOD_SUMMERY_REPORT(String lOCATION_CODE, String lOCATION_NAME, String cIRCLE_DESC, String rAO_NAME,
			String bILL_CYCLE_CODE, String bILL_CYCLE_DESCR, String nO_OF_CONSUMER, String nO_OF_CONSUMER_PREV_MONTH,
			String nO_OF_CONSUMER_BILLED, String nO_OF_CONS_BILLED_PREV_MONTH, String nET_ENERGY_IMP_KWH,
			String nET_ENERGY_IMP_KWH_PREV, String nET_ENERGY_GEN_KWH, String tOTAL_IMPORT, String tOTAL_IMPORT_PREV,
			String tOTAL_ENERGY_SOLD_TO_CONS, String tOTAL_ENERGY_SOLD_PREV_MONTH, String eNERGY_LOST,
			String eNERGY_LOST_PREV, String sYSTEM_LOSS, String sYSTEM_LOSS_PREV, String tOTAL_GROSS_BILLED_AMT,
			String tOTAL_GROSS_BILLED_PREV_MONTH, String tOTAL_NET_BILLED_AMT, String tOTAL_NET_BILLED_PREV_MONTH,
			String tOTAL_LPS_BILLED_AMT, String tOTAL_LPS_BILLED_PREV_MONTH, String tOTAL_GROSS_PRN_COLLECTED_AMT,
			String tOTAL_GROSS_PRN_COLL_PREV_MON, String tOTAL_GROSS_LPS_COLLECTED_AMT,
			String tOTAL_GROSS_LPS_COLL_PREV_MON, String tOTAL_GROSS_COLLECTED_AMT, String tOTAL_GROSS_COLL_PREV_MONTH,
			String cI_RATIO, String cI_RATIO_PREV, String aC_RECEIVABLE, String aC_RECEIVABLE_PREV_MONTH,
			String aC_RECEIVABLE_PRN_CUR_MON, String aC_RECEIVABLE_PRN_PREV_MONTH, String aC_RECEIVABLE_LPS_CUR_MON,
			String aC_RECEIVABLE_LPS_PREV_MONTH, String rEB_STATISTICS, String eNERGY_EXP_SOLD_TO_REB,
			String bILLED_AMT_TO_REB, String cOLL_AMT_F_REB, String aC_RECEIVABLE_F_REB, String sYSTEM_LOSS_WITHOUT_REB,
			String cI_RATIO_WITHOUT_REB, String bPDB_ESU_BILLING_RATE, String bPDB_ESU_BILLING_RATE_PREV,
			String lIVE_CONSUMER_PREV_MONTH, String pREV_NO_OF_CONS_BILLED, String pREV_MONTH_ENERGY_SOLD,
			String pREV_MONTH_RECEIVABLE_AMT) {
		super();
		LOCATION_CODE = lOCATION_CODE;
		LOCATION_NAME = lOCATION_NAME;
		CIRCLE_DESC = cIRCLE_DESC;
		RAO_NAME = rAO_NAME;
		BILL_CYCLE_CODE = bILL_CYCLE_CODE;
		BILL_CYCLE_DESCR = bILL_CYCLE_DESCR;
		NO_OF_CONSUMER = nO_OF_CONSUMER;
		NO_OF_CONSUMER_PREV_MONTH = nO_OF_CONSUMER_PREV_MONTH;
		NO_OF_CONSUMER_BILLED = nO_OF_CONSUMER_BILLED;
		NO_OF_CONS_BILLED_PREV_MONTH = nO_OF_CONS_BILLED_PREV_MONTH;
		NET_ENERGY_IMP_KWH = nET_ENERGY_IMP_KWH;
		NET_ENERGY_IMP_KWH_PREV = nET_ENERGY_IMP_KWH_PREV;
		NET_ENERGY_GEN_KWH = nET_ENERGY_GEN_KWH;
		TOTAL_IMPORT = tOTAL_IMPORT;
		TOTAL_IMPORT_PREV = tOTAL_IMPORT_PREV;
		TOTAL_ENERGY_SOLD_TO_CONS = tOTAL_ENERGY_SOLD_TO_CONS;
		TOTAL_ENERGY_SOLD_PREV_MONTH = tOTAL_ENERGY_SOLD_PREV_MONTH;
		ENERGY_LOST = eNERGY_LOST;
		ENERGY_LOST_PREV = eNERGY_LOST_PREV;
		SYSTEM_LOSS = sYSTEM_LOSS;
		SYSTEM_LOSS_PREV = sYSTEM_LOSS_PREV;
		TOTAL_GROSS_BILLED_AMT = tOTAL_GROSS_BILLED_AMT;
		TOTAL_GROSS_BILLED_PREV_MONTH = tOTAL_GROSS_BILLED_PREV_MONTH;
		TOTAL_NET_BILLED_AMT = tOTAL_NET_BILLED_AMT;
		TOTAL_NET_BILLED_PREV_MONTH = tOTAL_NET_BILLED_PREV_MONTH;
		TOTAL_LPS_BILLED_AMT = tOTAL_LPS_BILLED_AMT;
		TOTAL_LPS_BILLED_PREV_MONTH = tOTAL_LPS_BILLED_PREV_MONTH;
		TOTAL_GROSS_PRN_COLLECTED_AMT = tOTAL_GROSS_PRN_COLLECTED_AMT;
		TOTAL_GROSS_PRN_COLL_PREV_MON = tOTAL_GROSS_PRN_COLL_PREV_MON;
		TOTAL_GROSS_LPS_COLLECTED_AMT = tOTAL_GROSS_LPS_COLLECTED_AMT;
		TOTAL_GROSS_LPS_COLL_PREV_MON = tOTAL_GROSS_LPS_COLL_PREV_MON;
		TOTAL_GROSS_COLLECTED_AMT = tOTAL_GROSS_COLLECTED_AMT;
		TOTAL_GROSS_COLL_PREV_MONTH = tOTAL_GROSS_COLL_PREV_MONTH;
		CI_RATIO = cI_RATIO;
		CI_RATIO_PREV = cI_RATIO_PREV;
		AC_RECEIVABLE = aC_RECEIVABLE;
		AC_RECEIVABLE_PREV_MONTH = aC_RECEIVABLE_PREV_MONTH;
		AC_RECEIVABLE_PRN_CUR_MON = aC_RECEIVABLE_PRN_CUR_MON;
		AC_RECEIVABLE_PRN_PREV_MONTH = aC_RECEIVABLE_PRN_PREV_MONTH;
		AC_RECEIVABLE_LPS_CUR_MON = aC_RECEIVABLE_LPS_CUR_MON;
		AC_RECEIVABLE_LPS_PREV_MONTH = aC_RECEIVABLE_LPS_PREV_MONTH;
		REB_STATISTICS = rEB_STATISTICS;
		ENERGY_EXP_SOLD_TO_REB = eNERGY_EXP_SOLD_TO_REB;
		BILLED_AMT_TO_REB = bILLED_AMT_TO_REB;
		COLL_AMT_F_REB = cOLL_AMT_F_REB;
		AC_RECEIVABLE_F_REB = aC_RECEIVABLE_F_REB;
		SYSTEM_LOSS_WITHOUT_REB = sYSTEM_LOSS_WITHOUT_REB;
		CI_RATIO_WITHOUT_REB = cI_RATIO_WITHOUT_REB;
		BPDB_ESU_BILLING_RATE = bPDB_ESU_BILLING_RATE;
		BPDB_ESU_BILLING_RATE_PREV = bPDB_ESU_BILLING_RATE_PREV;
		LIVE_CONSUMER_PREV_MONTH = lIVE_CONSUMER_PREV_MONTH;
		PREV_NO_OF_CONS_BILLED = pREV_NO_OF_CONS_BILLED;
		PREV_MONTH_ENERGY_SOLD = pREV_MONTH_ENERGY_SOLD;
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
	}

	public BC_MOD_SUMMERY_REPORT() {
		super();
		// TODO Auto-generated constructor stub
	}

	
	

	
}
