package com.example.demo;

public class MOD_ENERGY_SOLD_REPORT {
	private String RAO_NAME;
	private String CIRCLE_NAME;
	private String LOCATION_CODE;
	private String LOCATION_NAME;
	private String BILL_MONTH;	
	private String CATEGORY;
	private String LIVE_CONSUMER_PREV_MONTH;
	private String NEW_CONSUMER_IN_MONTH;
	private String PD_CONSUMER_IN_MONTH;
	private String TTL_COUSTOMER;
	private String TD_CONSUMER;
	private String ACTIVE_CUSTOMER;
	private String BILLED_CONSUMER;
	private String TOTAL_ENERGY_SOLD;
	private String CATEGORY_IV;
	private String PREV_MONTH_BILLED_AMT;
	private String PREV_MONTH_RECEIVABLE_AMT;
	private String PREV_MONTH_COLLECTION_AMT;
	private String PREV_MONTH_ENERGY_SOLD;
	
	private String TOTAL_NEW_CONSUMER_IN_MONTH;
	
	@Override
	public String toString() {
		return "MOD_ENERGY_SOLD_REPORT [RAO_NAME=" + RAO_NAME + ", CIRCLE_NAME=" + CIRCLE_NAME + ", LOCATION_CODE="
				+ LOCATION_CODE + ", LOCATION_NAME=" + LOCATION_NAME + ", BILL_MONTH=" + BILL_MONTH + ", CATEGORY="
				+ CATEGORY + ", LIVE_CONSUMER_PREV_MONTH=" + LIVE_CONSUMER_PREV_MONTH + ", NEW_CONSUMER_IN_MONTH="
				+ NEW_CONSUMER_IN_MONTH + ", PD_CONSUMER_IN_MONTH=" + PD_CONSUMER_IN_MONTH + ", TTL_COUSTOMER="
				+ TTL_COUSTOMER + ", TD_CONSUMER=" + TD_CONSUMER + ", ACTIVE_CUSTOMER=" + ACTIVE_CUSTOMER
				+ ", BILLED_CONSUMER=" + BILLED_CONSUMER + ", TOTAL_ENERGY_SOLD=" + TOTAL_ENERGY_SOLD + ", CATEGORY_IV="
				+ CATEGORY_IV + ", PREV_MONTH_BILLED_AMT=" + PREV_MONTH_BILLED_AMT + ", PREV_MONTH_RECEIVABLE_AMT="
				+ PREV_MONTH_RECEIVABLE_AMT + ", PREV_MONTH_COLLECTION_AMT=" + PREV_MONTH_COLLECTION_AMT
				+ ", PREV_MONTH_ENERGY_SOLD=" + PREV_MONTH_ENERGY_SOLD + ", TOTAL_NEW_CONSUMER_IN_MONTH="
				+ TOTAL_NEW_CONSUMER_IN_MONTH + "]";
	}
	public String getRAO_NAME() {
		return RAO_NAME;
	}
	public void setRAO_NAME(String rAO_NAME) {
		RAO_NAME = rAO_NAME;
	}
	public String getCIRCLE_NAME() {
		return CIRCLE_NAME;
	}
	public void setCIRCLE_NAME(String cIRCLE_NAME) {
		CIRCLE_NAME = cIRCLE_NAME;
	}
	public String getLOCATION_CODE() {
		return LOCATION_CODE;
	}
	public void setLOCATION_CODE(String lOCATION_CODE) {
		LOCATION_CODE = lOCATION_CODE;
	}
	public String getLOCATION_NAME() {
		return LOCATION_NAME;
	}
	public void setLOCATION_NAME(String lOCATION_NAME) {
		LOCATION_NAME = lOCATION_NAME;
	}
	public String getBILL_MONTH() {
		return BILL_MONTH;
	}
	public void setBILL_MONTH(String bILL_MONTH) {
		BILL_MONTH = bILL_MONTH;
	}
	public String getCATEGORY() {
		return CATEGORY;
	}
	public void setCATEGORy(String cATEGORY) {
		CATEGORY = cATEGORY;
	}
	public String getLIVE_CONSUMER_PREV_MONTH() {
		return LIVE_CONSUMER_PREV_MONTH;
	}
	public void setLIVE_CONSUMER_PREV_MONTH(String lIVE_CONSUMER_PREV_MONTH) {
		LIVE_CONSUMER_PREV_MONTH = lIVE_CONSUMER_PREV_MONTH;
	}
	public String getNEW_CONSUMER_IN_MONTH() {
		return NEW_CONSUMER_IN_MONTH;
	}
	public void setNEW_CONSUMER_IN_MONTH(String nEW_CONSUMER_IN_MONTH) {
		NEW_CONSUMER_IN_MONTH = nEW_CONSUMER_IN_MONTH;
	}
	public String getPD_CONSUMER_IN_MONTH() {
		return PD_CONSUMER_IN_MONTH;
	}
	public void setPD_CONSUMER_IN_MONTH(String pD_CONSUMER_IN_MONTH) {
		PD_CONSUMER_IN_MONTH = pD_CONSUMER_IN_MONTH;
	}
	public String getTTL_COUSTOMER() {
		return TTL_COUSTOMER;
	}
	public void setTTL_COUSTOMER(String tTL_COUSTOMER) {
		TTL_COUSTOMER = tTL_COUSTOMER;
	}
	public String getTD_CONSUMER() {
		return TD_CONSUMER;
	}
	public void setTD_CONSUMER(String tD_CONSUMER) {
		TD_CONSUMER = tD_CONSUMER;
	}
	public String getACTIVE_CUSTOMER() {
		return ACTIVE_CUSTOMER;
	}
	public void setACTIVE_CUSTOMER(String aCTIVE_CUSTOMER) {
		ACTIVE_CUSTOMER = aCTIVE_CUSTOMER;
	}
	public String getBILLED_CONSUMER() {
		return BILLED_CONSUMER;
	}
	public void setBILLED_CONSUMER(String bILLED_CONSUMER) {
		BILLED_CONSUMER = bILLED_CONSUMER;
	}
	public String getTOTAL_ENERGY_SOLD() {
		return TOTAL_ENERGY_SOLD;
	}
	public void setTOTAL_ENERGY_SOLD(String tOTAL_ENERGY_SOLD) {
		TOTAL_ENERGY_SOLD = tOTAL_ENERGY_SOLD;
	}
	public String getCATEGORY_IV() {
		return CATEGORY_IV;
	}
	public void setCATEGORY_IV(String cATEGORY_IV) {
		CATEGORY_IV = cATEGORY_IV;
	}
	public String getPREV_MONTH_BILLED_AMT() {
		return PREV_MONTH_BILLED_AMT;
	}
	public void setPREV_MONTH_BILLED_AMT(String pREV_MONTH_BILLED_AMT) {
		PREV_MONTH_BILLED_AMT = pREV_MONTH_BILLED_AMT;
	}
	public String getPREV_MONTH_RECEIVABLE_AMT() {
		return PREV_MONTH_RECEIVABLE_AMT;
	}
	public void setPREV_MONTH_RECEIVABLE_AMT(String pREV_MONTH_RECEIVABLE_AMT) {
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
	}
	public String getPREV_MONTH_COLLECTION_AMT() {
		return PREV_MONTH_COLLECTION_AMT;
	}
	public void setPREV_MONTH_COLLECTION_AMT(String pREV_MONTH_COLLECTION_AMT) {
		PREV_MONTH_COLLECTION_AMT = pREV_MONTH_COLLECTION_AMT;
	}
	public String getPREV_MONTH_ENERGY_SOLD() {
		return PREV_MONTH_ENERGY_SOLD;
	}
	public void setPREV_MONTH_ENERGY_SOLD(String pREV_MONTH_ENERGY_SOLD) {
		PREV_MONTH_ENERGY_SOLD = pREV_MONTH_ENERGY_SOLD;
	}
	
	
	public String getTOTAL_NEW_CONSUMER_IN_MONTH() {
		return TOTAL_NEW_CONSUMER_IN_MONTH;
	}
	public void setTOTAL_NEW_CONSUMER_IN_MONTH(String tOTAL_NEW_CONSUMER_IN_MONTH) {
		TOTAL_NEW_CONSUMER_IN_MONTH = tOTAL_NEW_CONSUMER_IN_MONTH;
	}
	public void setCATEGORY(String cATEGORY) {
		CATEGORY = cATEGORY;
	}
	public MOD_ENERGY_SOLD_REPORT(String rAO_NAME, String cIRCLE_NAME, String lOCATION_CODE, String lOCATION_NAME,
			String bILL_MONTH, String cATEGORY, String lIVE_CONSUMER_PREV_MONTH, String nEW_CONSUMER_IN_MONTH,
			String pD_CONSUMER_IN_MONTH, String tTL_COUSTOMER, String tD_CONSUMER, String aCTIVE_CUSTOMER,
			String bILLED_CONSUMER, String tOTAL_ENERGY_SOLD, String cATEGORY_IV, String pREV_MONTH_BILLED_AMT,
			String pREV_MONTH_RECEIVABLE_AMT, String pREV_MONTH_COLLECTION_AMT, String pREV_MONTH_ENERGY_SOLD) {
		super();
		RAO_NAME = rAO_NAME;
		CIRCLE_NAME = cIRCLE_NAME;
		LOCATION_CODE = lOCATION_CODE;
		LOCATION_NAME = lOCATION_NAME;
		BILL_MONTH = bILL_MONTH;
		CATEGORY = cATEGORY;
		LIVE_CONSUMER_PREV_MONTH = lIVE_CONSUMER_PREV_MONTH;
		NEW_CONSUMER_IN_MONTH = nEW_CONSUMER_IN_MONTH;
		PD_CONSUMER_IN_MONTH = pD_CONSUMER_IN_MONTH;
		TTL_COUSTOMER = tTL_COUSTOMER;
		TD_CONSUMER = tD_CONSUMER;
		ACTIVE_CUSTOMER = aCTIVE_CUSTOMER;
		BILLED_CONSUMER = bILLED_CONSUMER;
		TOTAL_ENERGY_SOLD = tOTAL_ENERGY_SOLD;
		CATEGORY_IV = cATEGORY_IV;
		PREV_MONTH_BILLED_AMT = pREV_MONTH_BILLED_AMT;
		PREV_MONTH_RECEIVABLE_AMT = pREV_MONTH_RECEIVABLE_AMT;
		PREV_MONTH_COLLECTION_AMT = pREV_MONTH_COLLECTION_AMT;
		PREV_MONTH_ENERGY_SOLD = pREV_MONTH_ENERGY_SOLD;
	}
	public MOD_ENERGY_SOLD_REPORT() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public MOD_ENERGY_SOLD_REPORT(
			String tOTAL_NEW_CONSUMER_IN_MONTH) {
		super();
		
		TOTAL_NEW_CONSUMER_IN_MONTH = tOTAL_NEW_CONSUMER_IN_MONTH;
	}

}
